//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Axis3.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_Axis3_DIALOG                102
#define IDS_UNKNOWN_ERROR               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_GENERAL                     129
#define IDD_SPAWN                       130
#define IDR_MENU                        131
#define IDD_CHARTWEAK                   131
#define IDI_GENERAL                     132
#define IDD_ITEMS                       132
#define IDI_ZOOMOUT                     133
#define IDD_ITEMTWEAK                   133
#define IDI_ACCOUNT                     134
#define IDD_ACCOUNT                     134
#define IDI_ARROWDOWN                   135
#define IDD_MISC                        135
#define IDI_ARROWDOWNLEFT               136
#define IDD_LAUNCHER                    136
#define IDI_ARROWDOWNRIGHT              137
#define IDD_REMINDER                    137
#define IDI_ARROWLEFT                   138
#define IDD_TRAVEL                      138
#define IDI_ARROWRIGHT                  139
#define IDD_COMMANDS                    139
#define IDI_ARROWUP                     140
#define IDI_ARROWUPLEFT                 141
#define IDI_ARROWUPRIGHT                142
#define IDI_PALETTE                     143
#define IDI_EDITITEM                    144
#define IDI_EDITCHAR                    145
#define IDI_FIND                        146
#define IDI_HELP                        147
#define IDI_ITEMS                       148
#define IDI_LAUNCHER                    149
#define IDI_MISC                        150
#define IDI_CHAR                        151
#define IDI_REMINDER                    152
#define IDI_SETTINGS                    153
#define IDI_WORLD                       154
#define IDI_ZOOMIN                      155
#define IDI_COMMANDS                    156
#define IDD_COMPAGE                     159
#define IDI_OK                          160
#define IDI_CANCEL                      161
#define IDD_REMOTECONSOLEDLG            163
#define IDD_REMOTE_CONSOLE_LOGIN_DLG    164
#define IDD_PROFILE_LOGIN_DLG           165
#define IDD_CREATE_DB                   166
#define IDD_SEARCHCRITDLG               186
#define IDD_SETTING_GENERAL             237
#define IDD_SETTING_VIEWER              239
#define IDD_SETTINGEDIT                 245
#define IDD_LANGEDIT                    246
#define IDC_TAB                         1000
#define IDC_FINDAREA                    1000
#define IDC_COPYRIGHT                   1001
#define IDC_CLIENTBROWSE                1001
#define IDC_LICENSE                     1002
#define IDC_VERSION                     1002
#define IDC_AS_MULBROWSE                1002
#define IDC_MULBROWSE                   1002
#define IDC_SPFREEZE                    1002
#define IDC_SERVINFO                    1003
#define IDC_CLIENTS                     1004
#define IDC_EDIT                        1005
#define IDC_INFO                        1006
#define IDC_ADMIN                       1007
#define IDC_NUKE                        1008
#define IDC_DEFAULTCLIENT               1008
#define IDC_REMOVE                      1009
#define IDC_DEFUALTMULPATH              1009
#define IDC_DUPE                        1010
#define IDC_SHRINK                      1011
#define IDC_FLIP                        1012
#define IDC_LINK                        1013
#define IDC_RESTOCK                     1014
#define IDC_SAMPLES                     1015
#define IDC_XSCROLL                     1015
#define IDC_PURCHASES                   1016
#define IDC_YSCROLL                     1016
#define IDC_INVENTORY                   1017
#define IDC_SELL                        1018
#define IDC_BUY                         1019
#define IDC_GR_GMPAGE                   1020
#define IDC_GR_DISCIPLINE               1021
#define IDC_GR_SELF                     1022
#define IDC_GR_WEATHER                  1023
#define IDC_GR_VENDOR                   1024
#define IDC_GR_MISC                     1025
#define IDC_GR_INFORMATION              1026
#define IDC_LIGHTLEVEL                  1028
#define IDC_DRY                         1029
#define IDC_RAIN                        1030
#define IDC_SNOW                        1031
#define IDC_LIGHT_SLIDE                 1032
#define IDC_TELE                        1033
#define IDC_FIX                         1034
#define IDC_INVISIBLE                   1035
#define IDC_ALLMOVE                     1036
#define IDC_INVUL                       1037
#define IDC_BUTTONOK                    1037
#define IDC_ALWAYS_ONTOP                1037
#define IDC_SLIDERVALUE                 1038
#define IDC_MULTIVIEW_SCALE             1038
#define IDC_ALWAYS_ONTOP2               1038
#define IDC_DEVMODE                     1038
#define IDC_DEBUG                       1039
#define IDC_COMTAB                      1039
#define IDC_NIGHTSIGHT                  1040
#define IDC_SYSCLOSE                    1040
#define IDC_DETAIL                      1041
#define IDC_ADDTAB                      1041
#define IDC_GMTOGGLE                    1042
#define IDC_TABLABEL                    1042
#define IDC_HEARALL                     1043
#define IDC_BUTTONLABEL                 1043
#define IDC_VIEWERBGCOL                 1043
#define IDC_AS_USESAMEPATHASCLIENT      1043
#define IDC_ADDBUTTON                   1044
#define IDC_ITEMVIEW_SCALE              1044
#define IDC_RESURRECT                   1045
#define IDC_COM                         1045
#define IDC_VIEWERBG_COLOR              1045
#define IDC_DISCONNECT                  1046
#define IDC_COM_MACRO                   1046
#define IDC_KILL                        1047
#define IDC_FRAME_SELECT                1047
#define IDC_FORGIVE                     1048
#define IDC_JAIL                        1049
#define IDC_BUTTONCANCEL                1050
#define IDC_TABOK                       1052
#define IDC_TABCANCEL                   1053
#define IDC_ID_SEARCH                   1053
#define IDC_RE_CONSOLE                  1054
#define IDC_DEF_SEARCH                  1054
#define IDC_RESET_ITEM_CACHE            1054
#define IDC_CONSOLE_SEND                1055
#define IDC_DESC_SEARCH                 1055
#define IDC_RESET_MULTI_CACHE           1055
#define IDC_RESET_MAP_CACHE             1056
#define IDC_RESET_BGCOL                 1057
#define IDC_RECONNECT                   1058
#define IDC_IPADDRESS                   1059
#define IDC_MAPPLANE                    1059
#define IDC_COORDM                      1059
#define IDC_HOMEDIST                    1059
#define IDC_ACCT                        1060
#define IDC_COORDZ                      1060
#define IDC_PORT                        1061
#define IDC_SEARCH_VALUE                1061
#define IDC_COORDX                      1061
#define IDC_ACCTNAME                    1062
#define IDC_COORDY                      1062
#define IDC_PWD                         1063
#define IDC_PREFIX                      1063
#define IDC_SPORT                       1064
#define IDC_UOTITLE                     1064
#define IDC_SNAME                       1065
#define IDC_SIP                         1066
#define IDC_SNAME2                      1066
#define IDC_STATIC2                     1066
#define IDC_SACCT                       1067
#define IDC_SPASS                       1068
#define IDC_PAGEBAN                     1069
#define IDC_BROADCAST                   1069
#define IDC_PAGEDISCONNECT              1070
#define IDC_PAGEGOPLAYER                1071
#define IDC_PAGELIST                    1072
#define IDC_GR_PLEVEL                   1072
#define IDC_PAGEON                      1073
#define IDC_GR_RESDISP                  1073
#define IDC_GR_PRIVS                    1074
#define IDC_PAGEDELETE                  1075
#define IDC_PLV_0                       1075
#define IDC_PAGEJAIL                    1076
#define IDC_PLV_1                       1076
#define IDC_PAGEGOORIGIN                1077
#define IDC_PLV_2                       1077
#define IDC_PAGEQUEUE                   1078
#define IDC_PLV_3                       1078
#define IDC_PAGEOFF                     1079
#define IDC_PLV_4                       1079
#define IDC_PLV_5                       1080
#define IDC_PLV_6                       1081
#define IDC_PLV_7                       1082
#define IDC_SET_PLV                     1083
#define IDC_RDSP_0                      1084
#define IDC_RDSP_1                      1085
#define IDC_RDSP_2                      1086
#define IDC_RDSP_3                      1087
#define IDC_RDSP_4                      1088
#define IDC_RDSP_5                      1089
#define IDC_RDSP_6                      1090
#define IDC_PRIV02                      1091
#define IDC_WORLDSAVE                   1092
#define IDC_SET_RESDISP                 1092
#define IDC_SAVESTATICS                 1093
#define IDC_PRIVVALUE                   1093
#define IDC_RESYNC                      1094
#define IDC_RDSP_8                      1094
#define IDC_RESTOCKALL                  1095
#define IDC_LIST                        1095
#define IDC_RDSP_9                      1095
#define IDC_REMCONSOLE                  1096
#define IDC_FRAMETEXT                   1096
#define IDC_ADD                         1097
#define IDC_DATEPICKER                  1098
#define IDC_DELETE                      1099
#define IDC_SAVE                        1100
#define IDC_CANCEL                      1101
#define IDC_BROWSE                      1102
#define IDC_WEEKLY                      1103
#define IDC_DAILY                       1104
#define IDC_ONCE                        1105
#define IDC_NEVER                       1106
#define IDC_MONTHLY                     1107
#define IDC_WEEKDAY                     1108
#define IDC_STARTUP                     1109
#define IDC_TIMEPICKER                  1110
#define IDC_TITLE                       1111
#define IDC_PRIV08                      1112
#define IDC_GR_REMIND                   1112
#define IDC_PRIV010                     1113
#define IDC_GR_TIME                     1113
#define IDC_PRIV020                     1114
#define IDC_ST_TITLE                    1114
#define IDC_PRIV040                     1115
#define IDC_ART                         1115
#define IDC_PRIV0200                    1116
#define IDC_BUTTON1                     1116
#define IDC_CREATE                      1116
#define IDC_PRIV0400                    1117
#define IDC_MAP                         1117
#define IDC_PRIV0800                    1118
#define IDC_PRIV02000                   1119
#define IDC_LIST1                       1119
#define IDC_ITEMS                       1119
#define IDC_PRIV04000                   1120
#define IDC_PRIV080                     1121
#define IDC_TREE1                       1121
#define IDC_CATTREE                     1121
#define IDC_SET_PRIVS                   1122
#define IDC_CATDROP                     1122
#define IDC_SET_RESDISP3                1123
#define IDC_RESET_PRIVS                 1123
#define IDC_SUBDROP                     1123
#define IDC_DIRBROWSE                   1123
#define IDC_RDSP_7                      1124
#define IDC_RESETSTING                  1124
#define IDC_SEL                         1125
#define IDC_SELECT                      1125
#define IDC_SHERETABLE                  1125
#define IDC_STATIC1                     1126
#define IDC_GO                          1126
#define IDC_PROFILE_NAME                1127
#define IDC_SEND                        1127
#define IDC_WHERE                       1128
#define IDC_CHECK1                      1129
#define IDC_LOCKITEM                    1129
#define IDC_BUTTON2                     1130
#define IDC_TILE                        1130
#define IDC_EDIT1                       1131
#define IDC_ZTILE                       1131
#define IDC_VALUE                       1131
#define IDC_BUTTON3                     1132
#define IDC_BUTTON4                     1133
#define IDC_BUTTON5                     1134
#define IDC_FINDITEM                    1134
#define IDC_EDIT2                       1135
#define IDC_AMOUNT                      1135
#define IDC_ID                          1135
#define IDC_EDIT3                       1136
#define IDC_MAXDIST                     1136
#define IDC_LANGNAME                    1136
#define IDC_EDIT4                       1137
#define IDC_SPAWNRATE                   1137
#define IDC_LANGCODE                    1137
#define IDC_EDIT5                       1138
#define IDC_MINTIME                     1138
#define IDC_EDIT6                       1139
#define IDC_MAXTIME                     1139
#define IDC_BUTTON6                     1140
#define IDC_INIT                        1140
#define IDC_BUTTON7                     1141
#define IDC_PLACE                       1141
#define IDC_BUTTON8                     1142
#define IDC_EDIT7                       1143
#define IDC_NUKEARG                     1143
#define IDC_EDIT8                       1144
#define IDC_NUDGEAMOUNT                 1144
#define IDC_BUTTON9                     1145
#define IDC_MOVE1                       1145
#define IDC_BUTTON10                    1146
#define IDC_MOVE2                       1146
#define IDC_BUTTON11                    1147
#define IDC_MOVE4                       1147
#define IDC_BUTTON12                    1148
#define IDC_MOVE3                       1148
#define IDC_BUTTON13                    1149
#define IDC_MOVE8                       1149
#define IDC_BUTTON14                    1150
#define IDC_MOVE7                       1150
#define IDC_BUTTON15                    1151
#define IDC_MOVE6                       1151
#define IDC_BUTTON16                    1152
#define IDC_MOVE5                       1152
#define IDC_BUTTON17                    1153
#define IDC_ITEMID                      1153
#define IDC_BUTTON18                    1154
#define IDC_NUDGEDOWN                   1154
#define IDC_NUDGEUP                     1155
#define IDC_ADDEDIT                     1155
#define IDC_ADDLANG                     1156
#define IDC_DELDATA                     1157
#define IDC_LANGSELECT                  1158
#define IDC_STATICLANG                  1159
#define IDC_STATICNAME                  1160
#define IDC_STATICCODE                  1161
#define IDC_DELLANG                     1162
#define IDC_LLIST                       1163
#define IDC_LADDEDIT                    1164
#define IDC_LID                         1165
#define IDC_LVALUE                      1166
#define IDC_DELSETDATA                  1167
#define IDC_SETTINGSELECT               1168
#define IDC_STATICSETTYPE               1169
#define IDC_STATICCAT                   1170
#define IDC_STATICSUB                   1171
#define IDC_STATICMOVE                  1172
#define IDC_STATICNUDGE                 1173
#define IDC_STATICMAXAMOUNT             1174
#define IDC_STATICMAXDIST               1175
#define IDC_STATICMINTIME               1176
#define IDC_STATICMAXTIME               1177
#define IDC_STATICSPAWN                 1178
#define IDC_STATICZ                     1179
#define IDC_STATICSEARCH                1180
#define IDC_STATICVALUE                 1181
#define IDC_SETHOME                     1181
#define IDC_STATICINFO                  1182
#define IDC_SETHOMEDIST                 1182
#define IDC_LOCAL                       1184
#define IDC_SPHERETABLE                 1185
#define IDC_LOCATIONS                   1186
#define IDC_STATICMAP                   1187
#define IDC_STATICX                     1188
#define IDC_STATICY                     1189
#define IDC_STATICM                     1190
#define IDC_ZOOMOUT                     1379
#define IDC_ZOOMIN                      1380
#define ID_SETTINGS_GENERAL             32771
#define ID_SETTINGS_TRAVEL              32772
#define ID_PROFILE_OPTOINS              32773
#define ID_EXIT                         32774
#define ID_HELP32775                    32775
#define ID_EXIT_CLOSEAXIS               32776
#define ID_HELP_ABOUTAxis3              32777
#define ID_HELP_DOCUMENTATION           32778
#define ID_SETTINGS_PROFILE             32779
#define ID_SETTINGS_CREATEDATABASE      32780
#define ID_DATAEDIT_DEFAULTSETTINGS     32781
#define ID_DATAEDIT_LANGUAGE            32782
#define ID_SETTINGS_VIEWER              32783
#define IDC_STATIC_PREFIX               32784
#define IDC_STATIC_LANG                 32785
#define IDC_STATIC_DEFCLIENT            32786
#define IDC_STATIC_CLIENTTITLE          32787
#define IDC_STATIC_MULPATH              32788

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1191
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
